plugins {
    id 'com.android.application'
}

android {
    namespace 'cl.medina.llamadaflaite'
    compileSdk 35

    defaultConfig {
        applicationId 'cl.medina.llamadaflaite'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '0.3.0-alpha3'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:5.3.0'
}
